services:
  - type: web
    name: hybridx-backend
    env: node
    repo: https://github.com/Prakshit8/hybridX.git
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        value: mongodb+srv://hybridxUser:AD9vOytvvTEucKma@hybridonline.9j4osxl.mongodb.net/?appName=hybridOnline
      - key: DB_NAME
        value: hybridx
      - key: JWT_SECRET
        value: hybridx_jwt_secret_2025

  - type: web
    name: hybridx-frontend
    env: static
    repo: https://github.com/Prakshit8/hybridX.git
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://hybridx-uhj9.onrender.com/api
