
import mongoose from 'mongoose';
import bcrypt from 'bcrypt';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';


dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);


import User from '../models/User.js';


const spreadsheetStudents = {
  '11th': [
    {
      id: 41,
      name: "Priyank Mathur",
      email: "priyankmathur72@gmail.com",
      phone: "8003179114",
      class: "11th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 42,
      name: "Utkarsh Mishra",
      email: "utkarshmishrajodhpur99@gmail.com",
      phone: "7877636185",
      class: "11th",
      stream: "NEET",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 43,
      name: "Suhani Pediwal",
      email: "suhanipediwal818@gmail.com",
      phone: "7851919484",
      class: "11th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 44,
      name: "Bhawesh Mulchandani",
      email: "bhaweshmulchandani14@gmail.com",
      phone: "9461142733",
      class: "11th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 45,
      name: "Bhavya Mulchandani",
      email: "narendra11165@gmail.com",
      phone: "9461142733",
      class: "11th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 46,
      name: "Yashvi sadarangani",
      email: "Yashviritviksadarangani@gmail.com",
      phone: "9001922758",
      class: "11th",
      stream: "NEET",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 47,
      name: "Aastha gujrati",
      email: "aasthagujrati080@gmail.com",
      phone: "6378179515",
      class: "11th",
      stream: "NEET",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 48,
      name: "Charvi Mathur",
      email: "charvimathur68@gmail.com",
      phone: "8107230409",
      class: "11th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 49,
      name: "Khanak Lohra",
      email: "klshweta223@gmail.com",
      phone: "8233698257",
      class: "11th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 50,
      name: "Harsh chittara",
      email: "harshchittara05@gmail.com",
      phone: "7568198286",
      class: "11th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 51,
      name: "Rishit Rathi",
      email: "rishitrathirr0109@gmail.com",
      phone: "8890024663",
      class: "11th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 52,
      name: "Chirag haswani",
      email: "mahakhaswani0801@gmail.com",
      phone: "9352851388",
      class: "11th",
      stream: "NEET",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 53,
      name: "HARSHVARDHAN SONI",
      email: "Anjusoni3810@gmail.com",
      phone: "9929219826",
      class: "11th",
      stream: "NEET",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 54,
      name: "Tanvi Mathur",
      email: "mtanvi615@gmail.com",
      phone: "9358288243",
      class: "11th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 55,
      name: "Janhvi Purohit",
      email: "mcs01419@mcselearning.com",
      phone: "7976822021",
      class: "11th",
      stream: "NEET",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 56,
      name: "KHUSHI CHABDRAKAR",
      email: "sophiesxtae@gmail.com",
      phone: "9460147170",
      class: "11th",
      stream: "NEET",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 57,
      name: "BHAVYA MATHUR",
      email: "luvmathur6@gmail.com",
      phone: "9521603425",
      class: "11th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 58,
      name: "Dikshita Motwani",
      email: "jaymotwani13@gmail.com",
      phone: "6378754060",
      class: "11th",
      stream: "NEET",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 59,
      name: "Dhruv  Parihar",
      email: "dhruvdec28@gmail.com",
      phone: "7665119366",
      class: "11th",
      stream: "None of the above",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 60,
      name: "Zaheen Khan",
      email: "shaheenb293@gmail.com",
      phone: "8441035376",
      class: "11th",
      stream: "NEET",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 61,
      name: "Gyan Gaurav Maru",
      email: "gyangaurav2008@gmail.com",
      phone: "8949303660",
      class: "11th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 62,
      name: "Vidhi Solanki",
      email: "mamsolanki1986@gmail.com",
      phone: "9828496669",
      class: "11th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 63,
      name: "Riya poonar",
      email: "poonarcram84@gmail.com",
      phone: "8824641054",
      class: "11th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 64,
      name: "Ananya Agarwal",
      email: "ananyaagarwal4936@gmail.com",
      phone: "7878792048",
      class: "11th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 65,
      name: "Freya Bhargava",
      email: "bhargavafreya@gmail.com",
      phone: "9509552249",
      class: "11th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 66,
      name: "Gargee Mathur",
      email: "mathurgargee28@gmail.com",
      phone: "8239944000",
      class: "11th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 67,
      name: "Ayush gaur",
      email: "ayushgaur0808@gmail.com",
      phone: "8003890344",
      class: "11th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 68,
      name: "Dhanishtha Paldiya",
      email: "dhanishthapaldiya@gmail.com",
      phone: "9887898080",
      class: "11th",
      stream: "NEET",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 69,
      name: "Megha Khatri",
      email: "meghakhatrii09@gmail.com",
      phone: "7976332881",
      class: "11th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 70,
      name: "Mudit Soni",
      email: "soni.lalit79@gmail.com",
      phone: "7597801790",
      class: "11th",
      stream: "NEET",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 71,
      name: "Anirudh sharma",
      email: "2067@sacne.co.in",
      phone: "9928725773",
      class: "11th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    }
  ],
  '12th': [
    {
      id: 1,
      name: "Milin mathur",
      email: "milinmathur0@gmail.com",
      phone: "6378038398",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 2,
      name: "Preet Choudhary",
      email: "preet1112choudhary@gmail.com",
      phone: "7597359177",
      class: "12th",
      stream: "NEET",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 3,
      name: "Dhananjay Kaushish",
      email: "honeymaa1929@gmail.com",
      phone: "8171496200",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 4,
      name: "Yogesh Paliwal",
      email: "rajrajpaliwal64@gmail.com",
      phone: "9588998978",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 5,
      name: "Aradhya Mathur",
      email: "iamaradhya.01@gmail.com",
      phone: "8209362606",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 6,
      name: "Samarth Mathur",
      email: "mathursamarth748@gmail.com",
      phone: "8955842780",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 7,
      name: "Harshal Mathur",
      email: "Harshal28mathur@gmail.comh",
      phone: "8302429877",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 8,
      name: "Lakshya",
      email: "lakshyakhichar7@gmail.com",
      phone: "8107014688",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 9,
      name: "Kashvi Goil",
      email: "goilkashvi@gmail.com",
      phone: "9829026120",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 10,
      name: "Dhairy Solanki",
      email: "dhairysolanki125@gmail.com",
      phone: "8003147537",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 11,
      name: "Harshita chauhan",
      email: "sheelaparihar63@gmail.com",
      phone: "9461441473",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 12,
      name: "Divyanshu Limba",
      email: "limbadivyanshu@gmail.com",
      phone: "9588863100",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 13,
      name: "Himani Sankhla",
      email: "himanisankhla111@gmail.com",
      phone: "9119299311",
      class: "12th",
      stream: "NEET",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 14,
      name: "Yusuf Gazdhar",
      email: "yusufgazdhar9@gmail.com",
      phone: "9024600816",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 15,
      name: "Daksh pratap singh",
      email: "ratansingh15092008@gmail.com",
      phone: "8769506793",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 16,
      name: "Rajveer Singh Chauhan",
      email: "rajveerschauhan7788@gmail.com",
      phone: "9983968373",
      class: "12th",
      stream: "NEET",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 17,
      name: "Pratyaksh Motiani",
      email: "Pratyakshmotiani09@gmail.com",
      phone: "9079505000",
      class: "12th",
      stream: "NEET",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 18,
      name: "Surbhi Panwar",
      email: "surbhipanwarchb@gmail.com",
      phone: "7300070124",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 19,
      name: "Sahil Goyal",
      email: "sahilgoyal1808@gmail.com",
      phone: "8890819095",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 20,
      name: "Hitendrapal Singh Bhati",
      email: "bhatih488@gmail.com",
      phone: "8905558923",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 21,
      name: "Parvat Singh Rathore",
      email: "parvatsinghrathore1727@gmail.com",
      phone: "8696038717",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 22,
      name: "Bharat Singh Rajpurohit",
      email: "rajpurohitbharat800@gmail.com",
      phone: "6377970826",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 23,
      name: "Lakshya khatri",
      email: "lakshyakhatri654@gmail.com",
      phone: "8949718970",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 24,
      name: "Kartik lakhani",
      email: "kartiklakhani3107@gmail.com",
      phone: "9829659697",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 25,
      name: "Khushi Singh Tanwar",
      email: "Khushitanwar2605@gmail.com",
      phone: "7790989409",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 26,
      name: "Ravish Kumar",
      email: "ravishparwani1100@gmail.com",
      phone: "9784277624",
      class: "12th",
      stream: "NEET",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 27,
      name: "Dhritul Meghwal",
      email: "mdhritul@gmail.com",
      phone: "6376325209",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 28,
      name: "Ashmit Surana",
      email: "ashmitsurana02@gmail.com",
      phone: "9024674192",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 29,
      name: "Harsh",
      email: "Harsh.singh9950166216@gmail.com",
      phone: "09950166216",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 30,
      name: "Kanika mathur",
      email: "Kanikamathur2006@gmail.com",
      phone: "7597536954",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 31,
      name: "Priyawat Singh",
      email: "luckyc20072007@gmail.com",
      phone: "6377989449",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 32,
      name: "Kritishka Bhatnagar",
      email: "k76393465@gmail.com",
      phone: "7727811168",
      class: "12th",
      stream: "NEET",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 33,
      name: "Krishna Choudhary",
      email: "choudharymeena75@gmail.com",
      phone: "9636605508",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 34,
      name: "Chenansha rajpurohit",
      email: "Chenansharajpurohit23@gmail.com",
      phone: "6377008546",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 35,
      name: "Arisht Patwa",
      email: "patwaarisht01@gmail.com",
      phone: "7891212679",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 36,
      name: "Ashish Yadav",
      email: "geetayadav0571@gmail.com",
      phone: "9521058309",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 37,
      name: "Samanyu Mathur",
      email: "samritnitmthr@gmail.com",
      phone: "6375968949",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 38,
      name: "Aayushi",
      email: "neerugoyal0051@gmail.com",
      phone: "8233630405",
      class: "12th",
      stream: "JEE",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 39,
      name: "Jayshree kanwar",
      email: "Jayshree.kanwar.rathore987@gmail.com",
      phone: "9414440501",
      class: "12th",
      stream: "NEET",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    },
    {
      id: 40,
      name: "Zuhair rajawat",
      email: "siblings396@gmail.com",
      phone: "7014456556",
      class: "12th",
      stream: "NEET",
      fatherName: "Not provided",
      motherName: "Not provided",
      parentPhone1: "",
      parentPhone2: "",
    }
  ]
};

// Default password for migrated students (they should change this on first login)
const DEFAULT_PASSWORD = "hybridX@2025";

async function seedStudents() {
  try {
    console.log('🔄 Connecting to MongoDB...');
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✅ Connected to MongoDB');

    // Clear existing students (optional - comment out if you want to preserve existing data)
    console.log('🧹 Clearing existing student data...');
    await User.deleteMany({ role: 'student' });
    console.log('✅ Cleared existing student data');

    // Process all students from both classes
    const allStudents = [...spreadsheetStudents['11th'], ...spreadsheetStudents['12th']];
    let successCount = 0;
    let errorCount = 0;

    console.log(`📝 Starting migration of ${allStudents.length} students...`);

    for (const student of allStudents) {
      try {
        // Hash the default password
        const hashedPassword = await bcrypt.hash(DEFAULT_PASSWORD, 10);

        // Create user document matching the backend schema
        const userDoc = {
          name: student.name,
          email: student.email,
          password: hashedPassword,
          role: 'student',
          phone: student.phone,
          classLevel: student.class,
          batch: student.stream === 'JEE' ? 'Batch 1' : student.stream === 'NEET' ? 'Batch 2' : 'Batch 1',
          targetYear: new Date().getFullYear() + 1,
          
          // Flags for migrated students
          isMigratedStudent: true,
          hasChangedDefaultPassword: false,
          
          // Additional fields for migrated spreadsheet students
          spreadsheetData: {
            originalId: student.id,
            stream: student.stream,
            fatherName: student.fatherName,
            motherName: student.motherName,
            parentPhone1: student.parentPhone1,
            parentPhone2: student.parentPhone2,
            migratedAt: new Date()
          }
        };

        // Insert into database
        await User.create(userDoc);
        successCount++;
        console.log(`✅ Migrated: ${student.name} (${student.email})`);

      } catch (error) {
        errorCount++;
        if (error.code === 11000) {
          console.log(`⚠️  Skipped duplicate: ${student.email}`);
        } else {
          console.error(`❌ Error migrating ${student.name}:`, error.message);
        }
      }
    }

    console.log('\n📊 Migration Summary:');
    console.log(`✅ Successfully migrated: ${successCount} students`);
    console.log(`❌ Failed to migrate: ${errorCount} students`);
    console.log(`📝 Default password for all migrated students: ${DEFAULT_PASSWORD}`);
    console.log('\n🔐 Students should change their password after first login!');

  } catch (error) {
    console.error('❌ Migration failed:', error);
  } finally {
    await mongoose.disconnect();
    console.log('🔌 Disconnected from MongoDB');
  }
}

// Run the seeding function
seedStudents();
