const students = [
  {
    id: 41,
    name: "Priyank Mathur",
    email: "priyankmathur72@gmail.com",
    phone: "8003179114",
    class: "11th",
    stream: "JEE",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 42,
    name: "Utkarsh Mishra",
    email: "utkarshmishrajodhpur99@gmail.com",
    phone: "7877636185",
    class: "11th",
    stream: "NEET",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 43,
    name: "Suhani Pediwal",
    email: "suhanipediwal818@gmail.com",
    phone: "7851919484",
    class: "11th",
    stream: "JEE",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 44,
    name: "Bhawesh Mulchandani",
    email: "bhaweshmulchandani14@gmail.com",
    phone: "9461142733",
    class: "11th",
    stream: "JEE",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 45,
    name: "Bhavya Mulchandani",
    email: "narendra11165@gmail.com",
    phone: "9461142733",
    class: "11th",
    stream: "JEE",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 46,
    name: "Yashvi sadarangani",
    email: "Yashviritviksadarangani@gmail.com",
    phone: "9001922758",
    class: "11th",
    stream: "NEET",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 47,
    name: "Aastha gujrati",
    email: "aasthagujrati080@gmail.com",
    phone: "6378179515",
    class: "11th",
    stream: "NEET",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 48,
    name: "Charvi Mathur",
    email: "charvimathur68@gmail.com",
    phone: "8107230409",
    class: "11th",
    stream: "JEE",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 49,
    name: "Khanak Lohra",
    email: "klshweta223@gmail.com",
    phone: "8233698257",
    class: "11th",
    stream: "JEE",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 50,
    name: "Harsh chittara",
    email: "harshchittara05@gmail.com",
    phone: "7568198286",
    class: "11th",
    stream: "JEE",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 51,
    name: "Rishit Rathi",
    email: "rishitrathirr0109@gmail.com",
    phone: "8890024663",
    class: "11th",
    stream: "JEE",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 52,
    name: "Chirag haswani",
    email: "mahakhaswani0801@gmail.com",
    phone: "9352851388",
    class: "11th",
    stream: "NEET",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 53,
    name: "HARSHVARDHAN SONI",
    email: "Anjusoni3810@gmail.com",
    phone: "9929219826",
    class: "11th",
    stream: "NEET",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 54,
    name: "Tanvi Mathur",
    email: "mtanvi615@gmail.com",
    phone: "9358288243",
    class: "11th",
    stream: "JEE",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 55,
    name: "Janhvi Purohit",
    email: "mcs01419@mcselearning.com",
    phone: "7976822021",
    class: "11th",
    stream: "NEET",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 56,
    name: "KHUSHI CHABDRAKAR",
    email: "sophiesxtae@gmail.com",
    phone: "9460147170",
    class: "11th",
    stream: "NEET",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 57,
    name: "BHAVYA MATHUR",
    email: "luvmathur6@gmail.com",
    phone: "9521603425",
    class: "11th",
    stream: "JEE",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 58,
    name: "Dikshita Motwani",
    email: "jaymotwani13@gmail.com",
    phone: "6378754060",
    class: "11th",
    stream: "NEET",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 59,
    name: "Dhruv  Parihar",
    email: "dhruvdec28@gmail.com",
    phone: "7665119366",
    class: "11th",
    stream: "None of the above",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 60,
    name: "Zaheen Khan",
    email: "shaheenb293@gmail.com",
    phone: "8441035376",
    class: "11th",
    stream: "NEET",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 61,
    name: "Gyan Gaurav Maru",
    email: "gyangaurav2008@gmail.com",
    phone: "8949303660",
    class: "11th",
    stream: "JEE",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 62,
    name: "Vidhi Solanki",
    email: "mamsolanki1986@gmail.com",
    phone: "9828496669",
    class: "11th",
    stream: "JEE",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 63,
    name: "Riya poonar",
    email: "poonarcram84@gmail.com",
    phone: "8824641054",
    class: "11th",
    stream: "JEE",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 64,
    name: "Ananya Agarwal",
    email: "ananyaagarwal4936@gmail.com",
    phone: "7878792048",
    class: "11th",
    stream: "JEE",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 65,
    name: "Freya Bhargava",
    email: "bhargavafreya@gmail.com",
    phone: "9509552249",
    class: "11th",
    stream: "JEE",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 66,
    name: "Gargee Mathur",
    email: "mathurgargee28@gmail.com",
    phone: "8239944000",
    class: "11th",
    stream: "JEE",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 67,
    name: "Ayush gaur",
    email: "ayushgaur0808@gmail.com",
    phone: "8003890344",
    class: "11th",
    stream: "JEE",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 68,
    name: "Dhanishtha Paldiya",
    email: "dhanishthapaldiya@gmail.com",
    phone: "9887898080",
    class: "11th",
    stream: "NEET",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 69,
    name: "Megha Khatri",
    email: "meghakhatrii09@gmail.com",
    phone: "7976332881",
    class: "11th",
    stream: "JEE",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 70,
    name: "Mudit Soni",
    email: "soni.lalit79@gmail.com",
    phone: "7597801790",
    class: "11th",
    stream: "NEET",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  },
  {
    id: 71,
    name: "Anirudh sharma",
    email: "2067@sacne.co.in",
    phone: "9928725773",
    class: "11th",
    stream: "JEE",
    fatherName: "Not provided",
    motherName: "Not provided",
    parentPhone1: "",
    parentPhone2: "",
  }
];

export default students;
